apiVersion: v1
kind: Service
metadata:
  name: p-blog-wordpress-service
  namespace: production
  labels:
    run: p-blog-wordpress-service
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: p-blog-wordpress

---
apiVersion: v1
kind: Secret
metadata:
  name: p-blog-wordpress-secret
  namespace: production
type: Opaque
data:
  DB_USER: YWRtaW4=
  DB_PASS: a2V0aWxlbmc=

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: p-blog-wordpress
  namespace: production
spec:
  selector:
    matchLabels:
      run: p-blog-wordpress
  replicas: 2
  template:
    metadata:
      labels:
        run: p-blog-wordpress
    spec:
      containers:
      - image: $DOCKER_REGISTRY/$DOCKER_IMAGE_NAME:$BUILD_NUMBER
        name: p-blog-wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: "p-db-blog.cpa5p4d4immv.ap-southeast-1.rds.amazonaws.com"
        - name: WORDPRESS_DB_USER
          value: "admin" 
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: p-blog-wordpress-secret
              key: DB_PASS
        ports:
        - containerPort: 80
