apiVersion: v1
kind: Service
metadata:
  name: s-blog-wordpress-service
  namespace: staging
  labels:
    run: s-blog-wordpress-service
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: s-blog-wordpress

---
apiVersion: v1
kind: Secret
metadata:
  name: s-blog-wordpress-secret
  namespace: staging
type: Opaque
data:
  DB_USER: YWRtaW4=
  DB_PASS: V2liaXMwbjA=

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: s-blog-wordpress
  namespace: staging
spec:
  selector:
    matchLabels:
      run: s-blog-wordpress
  replicas: 2
  template:
    metadata:
      labels:
        run: s-blog-wordpress
    spec:
      containers:
      - image: $DOCKER_REGISTRY/$DOCKER_IMAGE_NAME:s-$BUILD_NUMBER
        name: s-blog-wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: "db-blog.cpa5p4d4immv.ap-southeast-1.rds.amazonaws.com"
        - name: WORDPRESS_DB_USER
          value: "admin" 
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: s-blog-wordpress-secret
              key: DB_PASS
        ports:
        - containerPort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: s-ingress
  namespace: staging
  annotations:
    ## Untuk menaikan batas upload file
    nginx.org/client-max-body-size: "10m"
    ## Memaksa jalan di https
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  rules:
    - host: blog.wibi.tech
      http:
        paths:
          - path: /
            backend:
              serviceName: s-blog-wordpress-service
              servicePort: 80